vitalityone/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path("", views.about, name="About")
]

vitalityone/fitness/urls.py
from django.urls import path
from . import views

app_name = 'fitness'

urlpatterns = [
    path("", views.fitnesshome, name="FitnessHome"),
    path("exercisedatabase/", views.exercisedatabase, name="ExerciseDb"),
    path("workoutscategories/", views.workoutscategories, name="WorkoutsCategories"),
    path("workoutscategories/workouts/<slug:url>", views.workouts, name="Workouts"),
    path("workoutscategories/workouts/posts/<slug:url>", views.posts, name="Posts"),
]

vitalityone/vitalityone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # Admin page honeypot
    # path('admin/', include('admin_honeypot.urls')),

    # Our actual admin page
    path('admin/', admin.site.urls),
    path('', views.home, name='Home'),
    path('termsCondition/', views.termsCondition, name='termsCondition'),
    path('policy/', views.policy, name='Policy'),
    path('about/', include('about.urls')),
    path('fitness/', include('fitness.urls')),
    path('nutrition/', include('nutrition.urls')),
    path('health/', include('health.urls')),
    path('tools/', include('tools.urls')),
    path('register/', include('loginsystem.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

vitalityone/fitness/models.py
from django.db import models
from django.utils import timezone
from django.utils.html import format_html
from ckeditor.fields import RichTextField
from django.utils.text import slugify
import os
from django.dispatch import receiver

# Create your models here.

# Insert Different Workouts Categories
class WorkoutCategory(models.Model):
    category_id = models.AutoField
    heading = models.CharField(max_length=40, default='')
    url = models.SlugField(max_length=100, blank=True)
    input_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.heading
    
    def save(self, *args, **kwargs):
        if not self.url:
            self.url = slugify(self.heading)
        super().save(*args, **kwargs)


def get_image_path(instance, filename):
    return os.path.join('fitness', 'workouts', str(instance.id), filename)


# Insert Multiple Workouts for same Categories
class Workout(models.Model):

# Workout Types
    WORKOUT_TYPES = [
        ('tb', 'Total Body'),
        ('ub', 'Upper Body'),
        ('lb', 'Lower Body'),
        ('cr', 'Core')
    ]

    workouts_id = models.AutoField
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    url = models.SlugField(max_length=100, blank=True)
    workout_time = models.IntegerField(default=10)
    workouts_type = models.CharField(max_length=5, choices=WORKOUT_TYPES, default='tb')
    input_date = models.DateTimeField(default=timezone.now)
    img = models.ImageField(upload_to='fitness/workouts')
    category = models.ForeignKey(WorkoutCategory, on_delete=models.CASCADE, related_name='workouts')

    def __str__(self):
        return self.title
    
    def img_tag(self):
        return format_html('<img src="/media/{}" style="width: 45px; height: 45px; border-radius: 50%;" />'.format(self.img))
    
    def save(self, *args, **kwargs):
        if not self.url:
            self.url = slugify(self.title)
        super().save(*args, **kwargs)

@receiver(models.signals.pre_delete, sender=Workout)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.img:
        if os.path.isfile(instance.img.path):
            os.remove(instance.img.path)

# Show the whole workout in an article form
class WorkoutPost(models.Model):
    post_id = models.AutoField
    workouts = models.ForeignKey(Workout, on_delete=models.CASCADE, related_name= 'workouts')
    description = RichTextField()
    url = models.SlugField(max_length=100, blank=True)
    author = models.CharField(max_length=100, default='Admin')
    publish_date = models.DateField(default=timezone.now)
    category = models.ForeignKey(WorkoutCategory, on_delete=models.CASCADE, default='', null=True, related_name= 'category')

    def save(self, *args, **kwargs):
        if not self.url:
            self.url = slugify(self.workouts)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.workouts}"

vitalityone/fitness/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from fitness.models import Workout, WorkoutCategory,WorkoutPost
from django.core.paginator import Paginator
import random
import requests
from decouple import config
# from django.contrib.auth.decorators import login_required


# Create your views here.
# @login_required(login_url='loginsystem:Login')
def fitnesshome(request):

    categories = WorkoutCategory.objects.all()[:4]

    return render(request, "fitness/fitness_homepage.html", {'categories': categories})

# @login_required(login_url='loginsystem:Login')
def workoutscategories(request):

    categories = WorkoutCategory.objects.all()
    context = {'categories': categories}
    return render(request, "fitness/fitness_workouts_categories.html", context)

# @login_required(login_url='loginsystem:Login')
def workouts(request, url):

    workoutsCatUrl = get_object_or_404(WorkoutCategory, url=url)
    workouts = workoutsCatUrl.workouts.all()
    posts = WorkoutPost.objects.all()

    context = {
        'workoutsCatUrl': workoutsCatUrl, 
        'workouts': workouts,
        'posts': posts,
    }
    return render(request, "fitness/fitness_workouts.html", context)

# @login_required(login_url='loginsystem:Login')
def posts(request, url):

    posts = WorkoutPost.objects.get(url=url)

    workouts = Workout.objects.all()

    nextpost = WorkoutPost.objects.filter(id__gt= posts.id).order_by('id').first()
    prevpost = WorkoutPost.objects.filter(id__lt= posts.id).order_by('id').last()

    # Get the category of the current post
    category = posts.category

    # Find all the posts that belong to the current category, excluding the current post
    related_posts = WorkoutPost.objects.filter(category=category).exclude(id=posts.id)

    # If there are not enough related posts for the current category, find additional related posts from other categories
    
    num_related_posts = 3

    if related_posts.count() > num_related_posts:
        related_posts = related_posts.order_by('-publish_date')[:num_related_posts]
    else:
    # not enough related posts in the same category, so include additional posts from other categories
        remaining_posts = num_related_posts - related_posts.count()
        additional_posts = WorkoutPost.objects.exclude(category=category).order_by('-publish_date')[:remaining_posts]
        related_posts = list(related_posts) + list(additional_posts)
        random.shuffle(related_posts)

    context = {
        'posts': posts,
        'nextpost': nextpost,
        'prevpost': prevpost,
        'related_posts': related_posts,
        'workouts': workouts,
    }
    return render(request, "fitness/fitness_workout_post.html", context)

# @login_required(login_url='loginsystem:Login')
def exercisedatabase(request):
    return render(request, "fitness/fitness_exercisedb.html")

vitalityone/fitness/templates/fitness/fitness_exercisedb.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Maximize Your Workouts with VitalityOne's Exercise Database {% endblock %}

{% block css %} <link rel="stylesheet" href="{% static 'fitness/CSS/_excercise_database.css' %}?now=U"> {% endblock %}

{% block content %}

<!--========== The Excercise Categories Option ==========-->

<section class="exercise_categories">
    <h1>Workouts</h1>
    <p>Categorize your Workouts with</p>
    <div class="cat-selection">
        <div class="category show-dropdown bodypart">
            <img src="{% static 'fitness/Materials/Icons/bodyparts.png' %}" alt="">
            <h2>Body Parts</h2>
        </div>
        <div class="category show-dropdown muscles">
            <img src="{% static 'fitness/Materials/Icons/muscle.png' %}" alt="">
            <h2>Target Muscles</h2>
        </div>
        <div class="category show-dropdown equipments">
            <img src="{% static 'fitness/Materials/Icons/equipments.png' %}" alt="">
            <h2>Equipments</h2>
        </div>
        <div class="category viewAll">
            <img src="{% static 'fitness/Materials/Icons/view.png' %}" alt="">
            <h2>View All</h2>
        </div>
    </div>
</section>

<!--=============== Notify Section ===============-->

<div class="updatesection">
    <div class="notify">
        <p class="notify-para">"Thank you for your interest in our Exercise Database. We are currently working on developing our Exercise Database and it will be available in the near future. Please check back soon for updates. Thank you for your patience." 🚧</p>
    </div>
</div>

{% endblock %}
    

vitalityone/fitness/templates/fitness/fitness_homepage.html
{% extends "base.html" %}

{% load static %}

{% block title %} Get Fit and Feel Great with VitalityOne {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'fitness/CSS/_fitness.css' %}?now=U">
{% endblock %}

{% block content %}

<!--========== The Hero section ==========-->

<section class="herosection">
    <div class="main-section __fitnessTitle__">
        <h2 class="title">Fit for Life</h2>
        <p class="subtitle">Start your journey to a healthier you today! Discover a world of fitness
            possibilities with our wide range of workouts </p>
    </div>
    <div class="imgBg __fitnessImg__">
        <img src="{% static 'fitness/Materials/Images/hero-section.png' %}" alt="">
    </div>
</section>

<!--========== The Workout section ==========-->

<section class="workout-section">
    <section class="workout-categories">
        <h1 class="workouts">Workouts</h1>

        <!--========== The Workout Programs ==========-->
        {% for category in categories|slice:":4" %}
        <section class="{{ category.heading }} __WorkoutProgram__" id="{{ category.heading }}">
            <div class="title-section">
                <span class="workout-title">{{ category.heading }}</span>
                <a href="workoutscategories/workouts/{{ category.url }}">View all {{ category.heading }}<i
                        class="ri-arrow-right-line"></i></a>
            </div>

            <div class="{{ category.heading }} __Program__">
                {% for workout in category.workouts.all|slice:":4" %}
                <div class="programs-card" onclick="window.location.href='workoutscategories/workouts/posts/{{workout.url}}';">
                    <div class="program-img">
                        <img src="{{ workout.img.url }} " loading="lazy" alt="">
                    </div>
                    <div class="content">
                        <p class="title">{{ workout.title }}</p>
                        <p class="desc">{{workout.description | truncatewords:8 | safe}}</p>
                        <p class="time-type"><span class="time">{{ workout.workout_time }} Min</span> <span
                                class="type">&#x2022; {{ workout.get_workouts_type_display }}</span></p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>

        {% endfor %}

        <a href="{% url 'fitness:WorkoutsCategories' %}" class="explore"><button type="button">Explore More</button></a>
    </section>
</section>

<!--========== The ExerciseDB Intro ==========-->

<div class="exercise-db" id="exercise-db">
    <h1 class="db-title">Exercise Database</h1>
    <div class="container">
        <img src="{% static 'fitness/Materials/Illustration/exerciseDb.gif' %}" alt="" class="__exerciseDBeImg__" loading="lazy">
        <div class="content __exerciseDBContent__">
            <h2 class="title">Browse More Than 1000 Exercises</h2>
            <p class="para">Get in shape and feel great with our exercise database - find the perfect workout
                for you and start sweating!</p>
            <a href="{% url 'fitness:ExerciseDb' %}"><button type="button">Try It Now</button></a>
        </div>
    </div>
</div>

{% endblock %}

vitalityone/fitness/templates/fitness/fitness_workout_post.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{ posts.workouts }} {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'fitness/CSS/_workout_post.css' %}?now=U">
{% endblock %}

{% block content %}

<article class="post">
  <div class="header">

    <h2 class="category_type">
      <span class="type">{{ posts.workouts.get_workouts_type_display }}</span>
    </h2>
    <div class="title">
      <h1 class="title__name"><span class="type">{{ posts.workouts }}</span></h1>
    </div>
    <div class="description">
      <h2 class="desc">{{ posts.workouts.description }}</h2>
    </div>
    <p class="posted_by">Posted on <span class="posted_on">{{ posts.publish_date }}</span> By <span class="author">{{ posts.author }}</span></p>

  </div>

  <div class="main-container">
    <div class="img-container">
      <img src="{{ posts.workouts.img.url }}">
    </div>
    <div class="content-container">
      <div class="content">

        {{ posts.description | safe }}

      </div>
    </div>
  </div>
</article>

<div class="pagination">
  <div class="prevpost">
    {% if prevpost %}
    <p onclick="window.location.href='{{ STATIC_URL }}/fitness/workoutscategories/workouts/posts/{{ prevpost.url }}'">
      <span>&#171;</span> {{prevpost}}</p>
    {% else %}
    <p onclick="window.location.href='/fitness/'"><span>&#171;</span> Home</p>
    {% endif %}
  </div>
  <div class="nextpost">
    {% if nextpost %}
    <p onclick="window.location.href='{{ STATIC_URL }}/fitness/workoutscategories/workouts/posts/{{ nextpost.url }}'">
      {{nextpost}} <span>&#187;</span></p>
    {% else %}
    <p onclick="window.location.href='/fitness/'">Home <span>&#187;</span></p>
    {% endif %}
  </div>
</div>

<section class="related-posts">
  <div class="title-section">
    <span class="title">Related Posts</span>
  </div>

  <div class="WorkoutPrograms">
    {% if related_posts %}
    {% for post in related_posts %}
    <div class="program">
      <div class="programs-card" onclick="window.location.href='{{post.url}}';">
        <div class="program-img">
        <img src="{{ post.workouts.img.url }}" alt="">
      </div>
      <div class="content">
        <p class="title">{{ post.workouts.title | safe }}</p>
        <p class="desc">{{ post.workouts.description | truncatewords:8 | safe }}</p>
        <p class="time-type"><span class="time">{{ post.workouts.workout_time }} Min</span> <span class="type">&#x2022; {{ post.workouts.get_workouts_type_display }}</span></p>
      </div>
    </div>
  </div>
  {% endfor %}
  {% endif %}
</div>
</section>

{% endblock %}

vitalityone/fitness/templates/fitness/fitness_workouts.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Transform Your Body with {{ workoutsCatUrl.heading }} {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'fitness/CSS/_workouts.css' %}?now=U">
{% endblock %}

{% block content %}

<!-- ========== The Workouts ========== -->
<section class="workout-categories">

    <div class="title-section __WorkoutProgram__">
        <span class="workout-title">{{ workoutsCatUrl.heading }}</span>
    </div>

    <section class="WorkoutPrograms  __Program__">
        {% if workouts %}
        {% for workout in workouts %}
        <div class="program">
            <div class="programs-card" onclick="window.location.href='posts/{{workout.url}}';">
                <div class="program-img">
                    <img src="{{ workout.img.url }}" alt="">
                </div>
                <div class="content">
                    <p class="title">{{ workout.title }}</p>
                    <p class="desc">{{ workout.description | truncatewords:8 | safe }}</p>
                    <p class="time-type"><span class="time">{{ workout.workout_time }} Min</span> <span class="type">&#x2022; {{ workout.get_workouts_type_display }}</span></p>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <p class="no-workout-msg">No workouts found</p>
        {% endif %}
    </section>

</section>

{% endblock %}

vitalityone/fitness/templates/fitness/fitness_workouts_categories.html
{% extends "base.html" %}

{% load static %}

{% block title %} VitalityOne's Workout Categories: A Path to a Healthier You {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'fitness/CSS/_workouts_categories.css' %}?now=U">
{% endblock %}

{% block content %}

<!--========== The All Workout section ==========-->

<section class="workout-section">
    <section class="workout-categories">
        <h1 class="workouts">Workouts</h1>

        <!--========== The Workout Programs ==========-->
        {% for category in categories %}
        {% if category.workouts.all %}
        <section class="{{ category.heading }} __WorkoutProgram__" id="{{ category.heading }}">
            <div class="title-section">
                <span class="workout-title">{{ category.heading }}</span>
                <a href="workouts/{{ category.url }}">View all {{ category.heading }}<i
                        class="ri-arrow-right-line"></i></a>
            </div>

            <div class="{{ category.heading }} __Program__">
                {% for workout in category.workouts.all|slice:":4" %}
                <div class="programs-card" onclick="window.location.href='workouts/posts/{{workout.url}}';">
                    <div class="program-img">
                        <img src="{{ workout.img.url }}" loading="lazy" alt="">
                    </div>
                    <div class="content">
                        <p class="title">{{ workout.title }}</p>
                        <p class="desc">{{workout.description | truncatewords:8 | safe}}</p>
                        <p class="time-type"><span class="time">{{ workout.workout_time }} Min</span> <span
                                class="type">&#x2022; {{ workout.get_workouts_type_display }}</span></p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>
        {% endif %}
        {% endfor %}

    </section>
</section>

{% endblock %}