vitalityone/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path("", views.about, name="About")
]

vitalityone/fitness/urls.py
from django.urls import path
from . import views

app_name = 'fitness'

urlpatterns = [
    path("", views.fitnesshome, name="FitnessHome"),
    path("exercisedatabase/", views.exercisedatabase, name="ExerciseDb"),
    path("workoutscategories/", views.workoutscategories, name="WorkoutsCategories"),
    path("workoutscategories/workouts/<slug:url>", views.workouts, name="Workouts"),
    path("workoutscategories/workouts/posts/<slug:url>", views.posts, name="Posts"),
]

vitalityone/health/urls.py
from django.urls import path
from . import views

app_name = 'health'

urlpatterns = [
    path("", views.healthhome, name="HealthHome"),
    path("healthcategories/", views.healthcategories, name="HealthCategories"),
    path("healthcategories/healthcategorypage/<slug:cat_url>", views.healthcategorypage, name="HealthCategoryPage"),
    path("healthcategories/post/<slug:post_url>", views.healthpost, name="HealthPost"),
]

vitalityone/nutrition/urls.py
from django.urls import path
from . import views

app_name = 'nutrition'

urlpatterns = [
    path("", views.nutritionhome, name="NutritionHome"),
    path("nutritioncategories/", views.nutritioncategories, name="NutritionCategories"),
    path("nutritioncategories/nutritioncategorypage/<slug:cat_url>", views.nutritioncategorypage, name="NutritionCategoryPage"),
    path("nutritioncategories/post/<slug:post_url>", views.nutritionpost, name="NutritionPost"),
]

vitalityone/tools/urls.py
from django.urls import path
from . import views

app_name = 'tools'

urlpatterns = [
    path("", views.toolshome, name="ToolsHome"),
]

vitalityone/vitalityone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # Admin page honeypot
    # path('admin/', include('admin_honeypot.urls')),

    # Our actual admin page
    path('admin/', admin.site.urls),
    path('', views.home, name='Home'),
    path('termsCondition/', views.termsCondition, name='termsCondition'),
    path('policy/', views.policy, name='Policy'),
    path('about/', include('about.urls')),
    path('fitness/', include('fitness.urls')),
    path('nutrition/', include('nutrition.urls')),
    path('health/', include('health.urls')),
    path('tools/', include('tools.urls')),
    path('register/', include('loginsystem.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

vitalityone/templates/base.html
{% load static %}

{% block head %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="VitalityOne offers articles on nutrients, health and fitness, along with tools such as 1RM, BMI, Water Intake, Body Composition, Calorie and Macro Calculator.">
    <meta name="keywords" content="VitalityOne, health and fitness, articles, nutrients, 1RM, BMI, Water Intake, Body Composition, Calorie Calculator, Macro Calculator">
    <meta name="robots" content="index, follow">
    <meta name="robots" content="index, follow">
    <title>{% block title %} {% endblock %}</title>

    <!--========== CSS FILES ==========-->

    <!--========== Favicons ==========-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'Materials/Icons/Favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'Materials/Icons/Favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'Materials/Icons/Favicon//favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'Materials/Icons/Favicon/site.webmanifest' %}">

    <!--========== CSS Links ==========-->

    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css?now=U" rel="stylesheet">

    {% endblock %}
    <link rel="stylesheet" href="{% static 'CSS/base.css' %}?now=U">
    <link rel="stylesheet" href="{% static 'CSS/modal.css' %}?now=U">
    {% block css %} {% endblock %}

</head>

<body>
    <!--========== The NavBar Begins Here ==========-->

    <nav class="nav-header">
        <div class="logo">
            <a href="{% url 'Home' %}"><img src="{% static 'Materials/Icons/logo.png' %}" title="Home"></a>
        </div>

        <div class="hamburger">
            <div class="hamburger--container">
                <div class="hamburger--bars">

                </div>
            </div>
        </div>
    </nav>

    <div class="fsmenu">
        <div class="fsmenu--container">
            <div class="fsmenu--text-block">
                <div class="fsmenu--text-container">
                    <ul class="fsmenu--list">
                        <li class="fsmenu--list-element">
                            <a href="{% url 'fitness:FitnessHome' %}">
                                <span>Fitness</span>
                            </a>
                            <div class="fsmenu--scrolling-text">
                                <span>Fitness</span><span>Fitness</span><span>Fitness</span><span>Fitness</span><span>Fitness</span>
                            </div>
                            <div class="fsmenu--link-img">
                                <div class="fsmenu--img-container">
                                    <img src="{% static 'Materials/Images/Home/navbar-f.jpg' %}">
                                </div>
                            </div>
                        </li>
                        <li class="fsmenu--list-element">
                            <a href="{% url 'nutrition:NutritionHome' %}">
                                <span>Nutrition</span>
                            </a>
                            <div class="fsmenu--scrolling-text">
                                <span>Nutrition</span><span>Nutrition</span><span>Nutrition</span><span>Nutrition</span><span>Nutrition</span>
                            </div>
                            <div class="fsmenu--link-img">
                                <div class="fsmenu--img-container">
                                    <img src="{% static 'Materials/Images/Home/navbar-n.jpg' %}">
                                </div>
                            </div>
                        </li>
                        <li class="fsmenu--list-element">
                            <a href="{% url 'health:HealthHome' %}">
                                <span>Health</span>
                            </a>
                            <div class="fsmenu--scrolling-text">
                                <span>Health</span><span>Health</span><span>Health</span><span>Health</span><span>Health</span>
                            </div>
                            <div class="fsmenu--link-img">
                                <div class="fsmenu--img-container">
                                    <img src="{% static 'Materials/Images/Home/navbar-h.jpg' %}">
                                </div>
                            </div>
                        </li>
                        <li class="fsmenu--list-element">
                            <a href="{% url 'tools:ToolsHome' %}">
                                <span>Tools</span>
                            </a>
                            <div class="fsmenu--scrolling-text">
                                <span>Tools</span><span>Tools</span><span>Tools</span><span>Tools</span><span>Tools</span>
                            </div>
                            <div class="fsmenu--link-img">
                                <div class="fsmenu--img-container">
                                    <img src="{% static 'Materials/Images/Home/navbar-t.jpg' %}">
                                </div>
                            </div>
                        </li>
                        <li class="fsmenu--list-element">
                            <a href="{% url 'about:About' %}">
                                <span>About Us</span>
                            </a>
                            <div class="fsmenu--scrolling-text">
                                <span>About</span><span>About</span><span>About</span><span>About</span><span>About</span>
                            </div>
                            <div class="fsmenu--link-img">
                                <div class="fsmenu--img-container">
                                    <img src="{% static 'Materials/Images/Home/navbar-a.jpg' %}">
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!--========== The NavaBar Section Ends ==========-->

    <!--========== The Body Styling Begins ==========-->

    <main>

        {% block content %} {% endblock %}

    </main>
    <!--========== The Body Styling Ends ==========-->

    <!--========= The Footer Starts =========-->

    <footer id="footer">

        <div class="footer-links-container">
            <div class="footer-logo">
                <div class="logo-container">
                    <a href="{% url 'Home' %}"><img src="{% static 'Materials/Icons/logo.png' %}" alt=""
                            title="Home"></a>
                </div>
                <p class="brand-name">VitalityOne<sup>™</sup></p>
            </div>

            <nav class="footer-links">
                <ul>
                    <li><a href="{% url 'fitness:FitnessHome' %}" class="title">Fitness</a></li>
                    <li><a href="{% url 'fitness:WorkoutsCategories' %}">Workout plans</a></li>
                    <li><a href="{% url 'fitness:WorkoutsCategories' %}workouts/beginner-training">Beginner Training
                            Workouts</a></li>
                    <li><a href="{% url 'fitness:WorkoutsCategories' %}workouts/strength-training">Strength Training
                            Workouts</a></li>
                    <li><a href="{% url 'fitness:WorkoutsCategories' %}workouts/cardiovascular-training">Cardio
                            Workouts</a></li>
                    <li><a href="{% url 'fitness:WorkoutsCategories' %}workouts/yoga-and-pilates">Yoga & Pilates
                            Workouts</a></li>
                    <li><a href="{% url 'fitness:ExerciseDb' %}">Exercise Database</a></li>
                </ul>
                <ul>
                    <li><a href="{% url 'nutrition:NutritionHome' %}" class="title">Nutrition</a></li>
                    <li><a
                            href="{% url 'nutrition:NutritionHome' %}nutritioncategories/nutritioncategorypage/healthy-recipes">Healthy
                            Recipes</a></li>
                    <li><a
                            href="{% url 'nutrition:NutritionHome' %}nutritioncategories/nutritioncategorypage/special-diets">Special
                            Diets</a></li>
                    <li><a
                            href="{% url 'nutrition:NutritionHome' %}nutritioncategories/nutritioncategorypage/nutrition-studies">Nutrition
                            Studies</a></li>
                    <li><a
                            href="{% url 'nutrition:NutritionHome' %}nutritioncategories/nutritioncategorypage/food-and-culture">Food
                            & Culture</a></li>
                    <li><a
                            href="{% url 'nutrition:NutritionHome' %}nutritioncategories/nutritioncategorypage/fad-diets">Fad
                            Diets</a></li>
                </ul>
                <ul>
                    <li><a href="{% url 'health:HealthHome' %}" class="title">Health</a></li>
                    <li><a href="{% url 'health:HealthHome' %}healthcategories/healthcategorypage/mental-health">Mental
                            Health & Wellness</a></li>
                    <li><a href="{% url 'health:HealthHome' %}healthcategories/healthcategorypage/physical-health">Physical
                            Health & Awareness</a></li>
                    <li><a href="{% url 'health:HealthHome' %}healthcategories/healthcategorypage/allergy-relief">Allergy
                            Relief</a></li>
                    <li><a href="{% url 'health:HealthHome' %}healthcategories/healthcategorypage/cancer-care">Cancer
                            Care</a></li>
                    <li><a href="{% url 'tools:ToolsHome' %}">Health Tools</a></li>
                </ul>
                <ul>
                    <li><a href="{% url 'about:About' %}" class="title">About Us</a></li>
                    <li><a href="{% url 'about:About' %}#team">Our Team</a></li>
                    <li><a href="{% url 'about:About' %}#aboutsection">Mission statement</a></li>
                    <li><a href="{% url 'about:About' %}#goals">Goals</a></li>
                    <li><a href="{% url 'about:About' %}#get-in-touch">Contact Us</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'loginsystem:Logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'loginsystem:Register' %}">Register</a></li>
                    {% endif %}
                </ul>
            </nav>

        </div>
        <div class="copyright-container">

            <div class="copyright">
                <span>Copyright &#169; 2023 Fitness Blender. All rights reserved. </span>
                <a href="{% url 'termsCondition' %}"><span class="sp">Terms and Conditions </span></a>
                <a href="{% url 'Policy' %}"><span class="sp">Privacy Policy </span></a>
            </div>

    </footer>

    <!--========= The Footer Ends =========-->

    <!--========= Scroll Up =========-->
    <a href="#" class="scrollup" id="scroll-up">
        <i class="ri-arrow-up-line"></i>
    </a>

    <!--========= JAVASCRIPT FILES =========-->

    <script src="{% static 'JS/scrollreveal.min.js' %}?now=U"></script>
    <script src="{% static 'JS/main.js' %}?now=U"></script>

    {% if not user.is_authenticated %}

    <!--========= Modal Popup HTML =========-->
    <div class="modal-container" id="cookiesPopup">
        <div class="cookiesContent">
            <button class="close">✖</button>
            <img src="{% static 'Materials/Icons/Modal/register.png' %}" alt="img" />
            <p>Join us now for an enhanced experience. Register today and explore more!</p>
            <button class="accept" onclick="window.location.href=`{% url 'loginsystem:Register' %}`;">Register</button>
        </div>
    </div>
    <!--========= Modal Popup JS =========-->
    <script src="{% static 'JS/modal.js' %}?now=U"></script>

    {% endif %}

    {% block js %} {% endblock %}
</body>

</html>

vitalityone/templates/homepage.html
{% extends 'base.html' %}

{% load static %}

{% block title %} VitalityOne: Your Key to a Healthy Lifestyle {% endblock %}

{% block css %} <link rel="stylesheet" href="{% static 'CSS/home.css' %}?now=U"> {% endblock %}

{% block content %}

<!--========== The Hero Section is here ==========-->

<section class="herosection">
    <video id="herobg" autoplay loop muted plays-inline>
        <source src="{% static 'Materials/Video/Home.mp4' %}" type="video/mp4">
    </video>
</section>

<!--========== The Fitness Section is here ==========-->

<section class="fitness">
    <div class="fitnessSection">
        <div class="content">
            <h1 class="title">Fitness</h1>
            <h2 class="subtitle">Start Your Transformation with Vitality One Fitness</h2>
            <p class="desc">Welcome to Vitality One Fitness, where we believe that fitness is not just about
                achieving a certain look or reaching a certain number on the scale. It's about feeling strong,
                healthy, and confident in your body, and living your best life.</p>
                <a href="{% url 'fitness:FitnessHome' %}"><button class="fitnessbtn">Explore</button></a>
        </div>
        <div class="fitnessBg">
            <img src="{% static 'Materials/Images/Home/fitness.jpg' %}" loading="lazy" alt="">
        </div>
    </div>
</section>

<!--========== The Nutrition Section is here ==========-->

<section class="nutrition">
    <div class="nutritionSection">
        <div class="content">
            <h1 class="title">Nutrition</h1>
            <h2 class="subtitle">Nutrition for Vibrant Living: Vitality One</h2>
            <p class="desc">Welcome to Vitality One Nutrition, where we're passionate about helping you fuel
                your life with vibrant, nutrient-dense foods. Our registered dietitians and nutrition experts
                offer personalized plans, ongoing support, and science-based education to help you achieve your
                goals and feel your best.</p>
                <a href="{% url 'nutrition:NutritionHome' %}"><button class="nutritionbtn">Explore</button></a>
        </div>
        <div class="nutritionBg">
            <img src="{% static 'Materials/Images/Home/nutrition.jpg' %}" loading="lazy" alt="">
        </div>
    </div>
</section>

<!--========== The Health Section is here ==========-->

<section class="health">
    <div class="healthSection">
        <div class="content">
            <h1 class="title">Health</h1>
            <h2 class="subtitle">Healthy Living, Elevated: Vitality One Health</h2>
            <p class="desc">Welcome to Vitality One Health, where we believe that optimal health is the
                foundation of a fulfilling life. Our comprehensive approach takes into account all aspects of
                your physical, mental, and emotional well-being. </p>
                <a href="{% url 'health:HealthHome' %}"><button class="healthbtn">Explore</button></a>
        </div>
        <div class="healthBg">
            <img src="{% static 'Materials/Images/Home/health.jpg' %}" loading="lazy" alt="">
        </div>
    </div>
</section>

<!--========== The Choose Us Section ==========-->

<div class="chooseUs">
    <h1 class="whyUs">Why Choose Us?</h1>
    <div class="content">
        <h1 class="title">Achieve Your Health Goals with Us</h1>
        <p class="desc">Our comprehensive resources, customized plans, and expert guidance can help you achieve
            your health and fitness goals faster and easier than ever before. Join our community and start your
            journey to a healthier you today.</p>
    </div>
    <div class="buttons">
        {% if not user.is_authenticated %} <!-- For Now until the new homepage is not designed -->
        <a href="{% url 'loginsystem:Register' %}"><button type="button" class="get_started">Get
                Started</button></a>
        {% endif %}
        <a href="{% url 'about:About' %}"><button type="button" class="learn_more">Learn More</button></a>
    </div>
</div>

<!--========== The Features Section ==========-->

<section class="features">
    <div class="f-slantedDiv">
        <h1 class="f-title">Our comprehensive health plans are perfect for everyone looking to live a healthier
            lifestyle
        </h1>
    </div>

    <div class="features-main">
        <h2 class="title">What Will You Get.</h2>
        <p class="subtitle">Make Your Workout Easier And Get Faster Results</p>
        <div class="features-cards">
            <div class="card">
                <div class="card-img">
                    <img src="{% static 'Materials/Icons/Home/fitness.png' %}" loading="lazy" alt="">
                </div>
                <div class="content">
                    <h3 class="c-title">Fitness Challenges</h3>
                    <p class="c-desc">Join our fun and exciting fitness challenges to stay motivated and track
                        your progress with others.</p>
                </div>
            </div>
            <div class="card">
                <div class="card-img">
                    <img src="{% static 'Materials/Icons/Home/article.png' %}" loading="lazy" alt="">
                </div>
                <div class="content">
                    <h3 class="c-title">Comprehensive Article Repository</h3>
                    <p class="c-desc"> Stay informed and make better choices with our engaging articles on
                        health, fitness, and nutrition.</p>
                </div>
            </div>
            <div class="card">
                <div class="card-img">
                    <img src="{% static 'Materials/Icons/Home/exercisedb.png' %}" loading="lazy" alt="">
                </div>
                <div class="content">
                    <h3 class="c-title">Extensive Exercise Database</h3>
                    <p class="c-desc"> Access an extensive library of exercises with step-by-step instructions,
                        images, and variations to help you create a custom workout plan.</p>
                </div>
            </div>
            <div class="card">
                <div class="card-img">
                    <img src="{% static 'Materials/Icons/Home/tools.png' %}" loading="lazy" alt="">
                </div>
                <div class="content">
                    <h3 class="c-title">Interactive Tools</h3>
                    <p class="c-desc">Stay on track and achieve your goals with easy-to-use tools like our BMI
                        and 1-rep max calculators and Many More.</p>
                </div>
            </div>
            <div class="card">
                <div class="card-img">
                    <img src="{% static 'Materials/Icons/Home/nutrition.png' %}" loading="lazy" alt="">
                </div>
                <div class="content">
                    <h3 class="c-title">Nutrition Guides</h3>
                    <p class="c-desc">Discover healthy eating habits, meal planning, and recipes with our
                        comprehensive nutrition guides.</p>
                </div>
            </div>
            <div class="card">
                <div class="card-img">
                    <img src="{% static 'Materials/Icons/Home/community.png' %}" loading="lazy" alt="">
                </div>
                <div class="content">
                    <h3 class="c-title">Community Support</h3>
                    <p class="c-desc"> Join our community of health and fitness enthusiasts for support,
                        motivation, and advice from others who share your goals.</p>
                </div>
            </div>
        </div>
    </div>
</section>

<!--========== The Latest Posts Section ==========-->

<section class="latest-posts" id="latest-posts">
    <div class="intro-section">
        <h1 class="p-title">Find Your Beginning</h1>
        <p class="p-desc">Navigating the Path: Unleashing the Potential Within</p>
    </div>

    <div class="posts">

    {% for workout in workouts %}

        <div class="post-card" onclick="window.location.href='fitness/workoutscategories/workouts/posts/{{workout.url}}';">
            <span class="card-title">{{ workout.category.heading }}</span>
            <div class="post-img">
                <img src=" {{ workout.img.url }}" loading="lazy" alt="">
            </div>
            <div class="content">
                <p class="title">{{workout.title}}</p>
                <p class="desc">{{workout.description | truncatewords:10 | safe}}</p>
                <p class="time-type"><span class="time">{{workout.workout_time}} Mins</span> <span class="type">&#x2022; {{ workout.get_workouts_type_display }}</span></p>
            </div>
        </div>

        {% endfor %}

    </div>
    <a href="{% url 'fitness:WorkoutsCategories' %}"><span>View all Programs</span></a>
</section>

{% endblock %}

vitalityone/templates/policy.html
{% extends 'base.html' %}

{% load static %}

{% block title %} VitalityOne: Privacy Policy {% endblock %}

{% block css %} <link rel="stylesheet" href="{% static 'CSS/TC_P.css' %}?now=U"> {% endblock %}

{% block content %}

<!--========== The Policy is here ==========-->

<div class="heading">
<h1 class="card-title">Privacy Policy</h1>
</div>

<p class="main-para">Protecting your privacy is important to us. This Privacy Policy explains how we collect, use, disclose, and safeguard your personal information when you use the Website. By using the Website, you consent to the practices described in this Privacy Policy.</p>

<p class="para"><span class="num">1.</span><span class="sub-head"> Information We Collect:</span> We may collect personal information, such as your name, email address, demographic information, and any other information you provide voluntarily when using the Website. We also collect non-personal information, such as your IP address, browser type, and device information, to analyze trends, administer the Website, and gather broad demographic information for aggregate use.</p>

<p class="para"><span class="num">2.</span><span class="sub-head"> Use of Information:</span> We use the information we collect to provide and improve the services and features offered on the Website, to personalize your experience, to send you relevant information and updates, and to respond to your inquiries or requests. We may also use the information to analyze user trends, conduct research, and enhance the security and integrity of the Website.</p>

<p class="para"><span class="num">3.</span><span class="sub-head"> Cookies and Similar Technologies:</span> We may use cookies, web beacons, and other similar technologies to collect and store certain information about your interactions with the Website. Cookies are small text files that are stored on your device to facilitate and enhance your browsing experience. You can manage your cookie preferences through your browser settings, but please note that disabling cookies may limit certain features and functionality of the Website.</p>

<p class="para"><span class="num">4.</span><span class="sub-head"> Data Security:</span> We take reasonable measures to protect the security of your personal information and to prevent unauthorized access, disclosure, or alteration. However, please be aware that no method of transmission over the Internet or electronic storage is completely secure. Therefore, while we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.</p>

<p class="para"><span class="num">5.</span><span class="sub-head"> Disclosure of Information:</span> We may disclose your personal information to third parties who perform services on our behalf or to comply with legal obligations. These third parties are obligated to use your information only as necessary to provide the requested services or as required by law. We do not sell, trade, or otherwise transfer your personal information to outside parties without your consent, except as described in this Privacy Policy.</p>

<p class="para"><span class="num">6.</span><span class="sub-head"> Children's Privacy:</span> The Website is not intended for individuals under the age of 13. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and believe that your child has provided us with personal information, please contact us, and we will take appropriate steps to remove that information from our systems.</p>

<p class="para"><span class="num">7.</span><span class="sub-head"> Changes to this Privacy Policy:</span> We reserve the right to modify this Privacy Policy at any time. Any changes will be effective immediately upon posting the revised Privacy Policy on the Website. We encourage you to review this Privacy Policy periodically for any updates or changes.</p>

{% endblock %}