vitalityone/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path("", views.about, name="About")
]

vitalityone/health/urls.py
from django.urls import path
from . import views

app_name = 'health'

urlpatterns = [
    path("", views.healthhome, name="HealthHome"),
    path("healthcategories/", views.healthcategories, name="HealthCategories"),
    path("healthcategories/healthcategorypage/<slug:cat_url>", views.healthcategorypage, name="HealthCategoryPage"),
    path("healthcategories/post/<slug:post_url>", views.healthpost, name="HealthPost"),
]

vitalityone/vitalityone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # Admin page honeypot
    # path('admin/', include('admin_honeypot.urls')),

    # Our actual admin page
    path('admin/', admin.site.urls),
    path('', views.home, name='Home'),
    path('termsCondition/', views.termsCondition, name='termsCondition'),
    path('policy/', views.policy, name='Policy'),
    path('about/', include('about.urls')),
    path('fitness/', include('fitness.urls')),
    path('nutrition/', include('nutrition.urls')),
    path('health/', include('health.urls')),
    path('tools/', include('tools.urls')),
    path('register/', include('loginsystem.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

vitalityone/health/models.py
import math
from django.db import models
from django.utils import timezone
from django.utils.html import format_html
from ckeditor.fields import RichTextField
from django.utils.text import slugify
import os
from PIL import Image

# Create your models here.

class HealthQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for post in self:
            post.delete()
        super().delete(*args, **kwargs)

class Tag(models.Model):
    TAG_SECTION = [
        ('HNews', 'News'),
        ('HTips', 'Tips & Tricks'),
    ]
    name = models.CharField(max_length=10, choices=TAG_SECTION, blank=True)

    def __str__(self):
        return self.name

# Health Categories

class HealthCategory(models.Model):

    CAT_SECTION = [
        ('ex', 'Explore'),
        ('hc', 'HealthCondition')
    ]

    category_id = models.AutoField(primary_key=True)
    cat_title = models.CharField(max_length=50, default='')
    description = models.CharField(max_length=100, default='')
    img = models.ImageField(upload_to='health/categories')
    sub_cat = models.CharField(max_length=2, choices=CAT_SECTION, default='ex')
    cat_url = models.SlugField(max_length=100, blank= True)
    input_date = models.DateTimeField(default=timezone.now)

    objects = HealthQuerySet.as_manager()

    def __str__(self):
        return self.cat_title

    def img_tag(self):
        return format_html('<img src="/media/{}" style="width: 45px; height: 45px; border-radius: 50%;" />'.format(self.img))
    
    def save(self, *args, **kwargs):
        if not self.cat_url:
            self.cat_url = slugify(self.cat_title)

        if self.pk is not None:  # object has already been saved to db
            old_self = HealthCategory.objects.get(pk=self.pk)
            if old_self.img != self.img:  # img field has changed
                if os.path.exists(old_self.img.path):
                    os.remove(old_self.img.path)
        
        super().save(*args, **kwargs)

        if self.img:
            if os.path.exists(self.img.path):
                img = Image.open(self.img.path)
                max_size = (800, 800)
                img.thumbnail(max_size)
                img.save(self.img.path, format='JPEG', optimize=True, quality=80)

    def delete(self, *args, **kwargs):
        if self.img and os.path.exists(self.img.path):
            os.remove(self.img.path)
        super().delete(*args, **kwargs)

# Health Post based on Categories

class HealthPost(models.Model):

    post_id = models.AutoField
    title = models.CharField(max_length=200)
    sub_description = models.CharField(max_length=200)
    description = RichTextField()
    author = models.CharField(max_length=100, default='Admin')
    post_url = models.SlugField(max_length=200, blank= True)
    img = models.ImageField(upload_to='health/posts')
    input_date = models.DateField(default=timezone.now)
    reading_time = models.IntegerField(default=10)
    tags = models.ManyToManyField(Tag, blank=True)
    category = models.ForeignKey(HealthCategory, on_delete=models.CASCADE, related_name='category')
    views = models.PositiveIntegerField(default=0)

    objects = HealthQuerySet.as_manager()

    def __str__(self):
        return self.title
    
    def img_tag(self):
        return format_html('<img src="/media/{}" style="width: 45px; height: 45px; border-radius: 50%;" />'.format(self.img))
    
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])
    
    def save(self, *args, **kwargs):
        if not self.post_url:
            self.post_url = slugify(self.title)
        
        if self.pk is not None:  # object has already been saved to db
            old_self = HealthPost.objects.get(pk=self.pk)
            if old_self.img != self.img:  # img field has changed
                if os.path.exists(old_self.img.path):
                    os.remove(old_self.img.path)
        
        words_per_minute =  183
        word_count = len(self.description.split())
        self.reading_time = math.ceil(word_count / words_per_minute)
        super().save(*args, **kwargs)

        if self.img:
            if os.path.exists(self.img.path):
                img = Image.open(self.img.path)
                max_size = (1280, 720)
                img.thumbnail(max_size)
                img.save(self.img.path, format='JPEG', optimize=True, quality= 80)

    def delete(self, *args, **kwargs):
        if self.img and os.path.exists(self.img.path):
            os.remove(self.img.path)
        super().delete(*args, **kwargs)

vitalityone/health/views.py
from django.shortcuts import render
from django.http import HttpResponse
from health.models import HealthCategory, HealthPost, Tag
import random
# from django.contrib.auth.decorators import login_required


# Create your views here.
# @login_required(login_url='loginsystem:Login')
def healthhome(request):

    healthcondition = HealthCategory.objects.filter(sub_cat='hc')
    explore = HealthCategory.objects.filter(sub_cat='ex')
    showpost = HealthPost.objects.all()

    top_articles = showpost.order_by('-input_date')[:2]
    top_reads = showpost.exclude(id__in=top_articles).order_by('-views')[:4]
    latest_news = HealthPost.objects.filter(tags__name__icontains='HNews').exclude(id__in=top_articles).exclude(id__in=top_reads).order_by('title')[:4]


    # pass the remaining posts to the template and render them
    context = {
        'healthcondition': healthcondition,
        'explore': explore,
        'showpost': showpost,
        'top_articles': top_articles,
        'top_reads': top_reads,
        'latest_news': latest_news,
     }

    return render(request, "health/health_homepage.html", context)

# @login_required(login_url='loginsystem:Login')

def healthcategories(request):

    categories = HealthCategory.objects.all()

    subcategory = request.GET.get('subcategory')

    if subcategory == 'hc':
        categories = HealthCategory.objects.filter(sub_cat='hc')
    elif subcategory == 'ex':
        categories = HealthCategory.objects.filter(sub_cat='ex')
    else:
        categories = HealthCategory.objects.all()

    posts = HealthPost.objects.all()


    context = {
        'categories': categories,
        'posts': posts,
        }
    return render(request, "health/health_categories.html", context)

# @login_required(login_url='loginsystem:Login')
def healthcategorypage(request, cat_url):

    category = HealthCategory.objects.get(cat_url=cat_url)
    posts = HealthPost.objects.filter(category= category)

    featured_posts = posts.order_by('-input_date')[:2]
    best_in_posts = posts.exclude(id__in=featured_posts).order_by('reading_time')[:4]
    more_in_posts = posts.exclude(id__in=featured_posts).exclude(id__in=best_in_posts).order_by('title')[:6]

    context = {
        'category': category,
        'featured_posts': featured_posts,
        'best_in_posts': best_in_posts,
        'more_in_posts': more_in_posts,
    }

    return render(request, "health/health_category_page.html", context)

def healthpost(request, post_url):

    posts = HealthPost.objects.get(post_url = post_url)

    posts.increase_views() # increase views by 1

    nextpost = HealthPost.objects.filter(id__gt= posts.id).order_by('id').first()
    prevpost = HealthPost.objects.filter(id__lt= posts.id).order_by('id').last()

    category = posts.category

    related_posts_same_category = HealthPost.objects.filter(category=category).exclude(post_url=posts.post_url).order_by('-input_date')
    related_posts_other_categories = HealthPost.objects.exclude(category=category)
    related_posts = list(related_posts_same_category) + list(related_posts_other_categories)
    random.shuffle(related_posts)
    
    context = {
        'posts': posts,
        'nextpost': nextpost,
        'prevpost': prevpost,
        'related_posts':related_posts
    }

    return render(request, "health/health_posts.html", context)

vitalityone/health/templates/health/health_categories.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Health & Wellness Guide {% endblock %}

{% block css %} 
    <link rel="stylesheet" href="{% static 'health/CSS/_categories.css' %}?now=U">
{% endblock %}

{% block content %}

<!-- ========== The Health Categories ========== -->

<section class="health-categories">
    <div class="title-section">
        <span class="category-title">Health & Wellness Guide</span>
    </div>
    
    <section class="HealthTopics">

        {% for category in categories %}
        {% if category.sub_cat %}

        <div class="topics">
            <div class="topics-card" onclick="window.location.href='healthcategorypage/{{category.cat_url}}'">
                <div class="topics-img">
                    <img src="{{ category.img.url }}" alt="">
                </div>
                <div class="content">
                    <h2 class="title">{{ category.cat_title }}</h2>
                    <p class="desc">{{ category.description }}</p>
                    <a href="healthcategorypage/{{category.cat_url}}">Go to Topic <i class="ri-arrow-right-line"></i></a>
                </div>
            </div>
        </div>

        {% endif %}
        {% endfor %}
    </section>

</section>

{% endblock %}

vitalityone/health/templates/health/health_category_page.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{ category.cat_title | safe }} {% endblock %}

{% block css %} 
    <link rel="stylesheet" href="{% static 'health/CSS/_categories_page.css' %}?now=U"> 
{% endblock %}

{% block content %}

<!--========= The Heading Section =========-->
<div class="Heading">
    <h1 class="card-title">{{ category.cat_title  | safe }}</h1>
    <p class="card-para">{{ category.description  | truncatewords:14 | safe }}</p>
</div>

<!--========= The Featured Section =========-->
{% if featured_posts %}
<section class="featured" id="featured">
    <h2 class="title">Featured</h2>
    <div class="f-container">
        {% for post in featured_posts %}
        <div class="container" onclick="window.location.href='/health/healthcategories/post/{{ post.post_url }}';">
            <div class="f-img">
                <img src="{{ post.img.url }}" loading="lazy" alt="">
            </div>
            <div class="content">
                <h1 class="article-title">{{ post.title | safe }}</h1>
                <p class="article-para">{{ post.sub_description | truncatewords:14 | safe }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endif %}
<!--========= The Best Of Section =========-->

{% if best_in_posts %}
<section class="best" id="best">
    <h2 class="title">Best In {{ category.cat_title }}</h2>
    <div class="b-container">
        {% for post in best_in_posts %}
        <div class="container" onclick="window.location.href='/health/healthcategories/post/{{ post.post_url }}';">
            <div class="b-img">
                <img src="{{ post.img.url }}" loading="lazy" alt="">
            </div>
            <div class="content">
                <h1 class="article-title">{{ post.title | safe }}</h1>
                <p class="article-para">{{ post.sub_description | truncatewords:14 | safe }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endif %}

<!--========= The More Section =========-->

{% if more_in_posts %}
<section class="more" id="more">
    <h2 class="title">More In {{ category.cat_title }}</h2>
    <div class="m-container">
        {% for post in more_in_posts %}
        <div class="container" onclick="window.location.href='/health/healthcategories/post/{{ post.post_url }}';">
            <div class="m-img">
                <img src="{{ post.img.url }}" loading="lazy" alt="">
            </div>
            <div class="content">
                <h1 class="article-title">{{ post.title | safe }}</h1>
                <p class="article-para">{{ post.sub_description | truncatewords:14 | safe }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endif %}

{% endblock %}

vitalityone/health/templates/health/health_homepage.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Revitalize Your Health with VitalityOne {% endblock %}

{% block css %} 
    <link rel="stylesheet" href="{% static 'health/CSS/_health.css' %}?now=U"> 
{% endblock %}

{% block content %}

<!--========= The Top-Articles Section =========-->

<section class="top-Articles" id="top-Articles">

    {% for homepost in top_articles %}
    <div class="container c-1 __healthArticles__" onclick="window.location.href='healthcategories/post/{{homepost.post_url}}';">
        <img src="{{ homepost.img.url }}" alt="">
        <div class="card">
            <h1 class="card-title">{{ homepost.title | truncatewords:6 | safe }}</h1>
            <p class="card-para">{{ homepost.sub_description | truncatewords:14 | safe }}</p>
        </div>
    </div>
    {% endfor %}

</section>


<!--========= The Explore Section Through Fields =========-->


<section class="explore-container __healthExplore__" id="explore-container">
    <div class="explore">
        <span class="explore_by">Explore By</span>
        <a href="{% url 'health:HealthCategories' %}?subcategory=ex">View all <i class="ri-arrow-right-line"></i></a>
    </div>
    <div class="container __healthExplore__">
        {% for healthex in explore.all|slice:":5" %}
        <div class="{{ healthex.cat_title }} explore-cat" onclick="window.location.href='healthcategories/healthcategorypage/{{healthex.cat_url}}';">
            <div class="cat-img">
                <img src="{{ healthex.img.url }}" loading="lazy" alt="">
            </div>
            <h3 class="cat-title">{{ healthex.cat_title }}</h3>
        </div>
        {% endfor %}
    </div>
</section>

<!--========= The Top Reads Section =========-->

<section class="top-read __healthRead__" id="top-read">
    <h2 class="title">Top Reads</h2>
    <div class="tr-container __healthRead__">
        {% for homepost in top_reads %}
            <div class="container" onclick="window.location.href='healthcategories/post/{{homepost.post_url}}';">
                <div class="tread-img">
                    <img src="{{ homepost.img.url }}" loading="lazy" alt="">
                </div>
                <div class="content">
                    <h1 class="article-title">{{ homepost.title | safe }}</h1>
                    <p class="article-para">{{ homepost.sub_description | truncatewords:14 | safe }}</p>
                </div>
            </div>
       {% endfor %}
    </div>
</section>

<!--========= The Trending Topics Section =========-->

<section class="trending __healthTrending__" id="trending">
    <h2 class="title">Trending Topics</h2>
    <div class="trend-btn __healthTrending__">
        <div class="trends">
            <span class="trend-topic"><a href="https://www.google.com/search?q=Mental+Health" target="_blank">Mental Health</a></span>
        </div>
        <div class="trends">
            <span class="trend-topic"><a href="https://www.google.com/search?q=Plant-Based+Diets" target="_blank">Plant-Based Diets</a></span>
        </div>
        <div class="trends">
            <span class="trend-topic"><a href="https://www.google.com/search?q=Gut+Health" target="_blank">Gut Health</a></span>
        </div>
        <div class="trends">
            <span class="trend-topic"><a href="https://www.google.com/search?q=Epigenetics" target="_blank">Epigenetics</a></span>
        </div>
        <div class="trends">
            <span class="trend-topic"><a href="https://www.google.com/search?q=Integrative+Medicine" target="_blank">Integrative Medicine</a></span>
        </div>
        <div class="trends">
            <span class="trend-topic"><a href="https://www.google.com/search?q=Infectious+Diseases" target="_blank">Infectious Diseases</a></span>
        </div>
        <div class="trends">
            <span class="trend-topic"><a href="https://www.google.com/search?q=Digital+Health" target="_blank">Digital Health</a></span>
        </div>
        <div class="trends">
            <span class="trend-topic"><a href="https://www.google.com/search?q=Precision+Medicine" target="_blank">Precision Medicine</a></span>
        </div>
        <div class="trends">
            <span class="trend-topic"><a href="https://www.google.com/search?q=Healthy+Aging" target="_blank">Healthy Aging</a></span>
        </div>
        <div class="trends">
            <span class="trend-topic"><a href="https://www.google.com/search?q=Metabolic+Health" target="_blank">Metabolic Health</a></span>
        </div>
        <div class="trends">
            <span class="trend-topic"><a href="https://www.google.com/search?q=Genetic+Testing" target="_blank">Genetic Testing</a></span>
        </div>
        <div class="trends">
            <span class="trend-topic"><a href="https://www.google.com/search?q=Artificial+Skin" target="_blank">Artificial Skin</a></span>
        </div>
    </div>
</section>

<!--========= The Health Conditions Section  =========-->

<section class="health-conditions __healthConditions__" id="health-conditions">
    <div class="healthco">
        <span class="h_condition-title">Health Conditions</span>
        <a href="{% url 'health:HealthCategories' %}?subcategory=hc">View all <i class="ri-arrow-right-line"></i></a>
    </div>
    <div class="container __healthConditions__">
        {% for healthcon in healthcondition.all|slice:":5" %}
        <div class="{{ healthcon.cat_title }} cat-condition" onclick="window.location.href='healthcategories/healthcategorypage/{{healthcon.cat_url}}';">
            <div class="cat-img">
                <img src="{{ healthcon.img.url }}" loading="lazy" alt="">
            </div>
            <h3 class="cat-title">{{ healthcon.cat_title }}</h3>
        </div>
        {% endfor %}
    </div>
</section>

<!--========= The Latest News And Updates Section  =========-->

<section class="latest-news __healthNews__" id="latest-news">
    <h2 class="title">Healthy Headlines</h2>
    <div class="news-container __healthNews__">
        {% for homepost in latest_news %}
            <div class="container" onclick="window.location.href='healthcategories/post/{{homepost.post_url}}';">
                <img src="{{ homepost.img.url }}" loading="lazy" alt="">
                <span class="news-title">{{ homepost.title| truncatewords:6 | safe }}</span>
            </div>
        {% endfor %}
    </div>
</section>

{% endblock %}

vitalityone/health/templates/health/health_posts.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{ posts.title }} {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'health/CSS/_posts.css' %}?now=U">
{% endblock %}

{% block content %}

<article>
    <div class="article-cover">
        <p id="date">{{ posts.input_date }} <span class="dot"></span>{{ posts.reading_time }} min read</p>
        <div class="tags">
            {% if posts.tags %}
            {% for tag in posts.tags.all %}
              <a>{{ tag.get_name_display }}</a>
            {% endfor %}
          {% endif %}
        <a onclick="window.location.href='/health/healthcategories/healthcategorypage/{{ posts.category.cat_url }}';">{{ posts.category.cat_title }}</a>
        </div>

        <div class="header">
            <p id="mobile-date">{{ posts.input_date }}<br /><span class="dot"></span>{{ posts.reading_time }} min read</p>
            <h1 class="article-title">{{ posts.title }}</h1>
            <img src="{{ posts.img.url }}"
                alt="{{ posts.title }}" class="hero-image">
        </div>
    </div>

    <div class="content-container">
        <div class="content">
            {{ posts.description | safe }}
        </div>
    </div>

    <p>Posted By <span class="posted_by">{{ posts.author }}</span></p>
</article>

<div class="pagination">
    <div class="prevpost">
      {% if prevpost %}
      <p onclick="window.location.href='{{ STATIC_URL }}/health/healthcategories/post/{{ prevpost.post_url }}'">
        <span>&#171;</span> {{prevpost}}</p>
      {% else %}
      <p onclick="window.location.href='/health/'"><span>&#171;</span> Home</p>
      {% endif %}
    </div>
    <div class="nextpost">
      {% if nextpost %}
      <p onclick="window.location.href='{{ STATIC_URL }}/health/healthcategories/post/{{ nextpost.post_url }}'">
        {{nextpost}} <span>&#187;</span></p>
      {% else %}
      <p onclick="window.location.href='/health/'">Home <span> &#187;</span></p>
      {% endif %}
    </div>
  </div>

<!--========= The Related Posts Section =========-->

<section class="related-post" id="related-post">
    <h2 class="title">Related Posts</h2>
    <div class="rp-container">
        {% for related_post in related_posts|slice:":4" %}
        <div class="container" onclick="window.location.href='{{related_post.post_url}}';">
            <div class="rel-img">
                <img src="{{ related_post.img.url }}" loading="lazy" alt="">
            </div>
            <div class="content">
                <h1 class="article-title">{{ related_post.title | safe }}</h1>
                <p class="article-para">{{ related_post.sub_description | truncatewords:14 | safe }}</p>
            </div>
        </div>
       {% endfor %}
    </div>
</section>


{% endblock %}